"""Alembic revision (generated).

This revision file was generated by `alembic revision`. It was edited to remove
accidental template placeholders so the file is valid Python.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '18af15ae8ac6'
down_revision = '52a8a35fd055'
branch_labels = None


def upgrade():
    pass


def downgrade():
    pass
