import { describe, expect, it } from 'vitest'

import {
  buildDeleteTemplate,
  buildInsertTemplate,
  buildSelect,
  buildUpdateTemplate,
  canEditRows,
  isAutoGenerated,
  isNumericType,
  qualify,
  quoteIdentifier,
  quoteValue,
  rowKey,
  statementAtCursor,
  toCsv,
  toJson,
} from '../lib/sql'
import type { ColumnInfo, TableStructure } from '../types'

function column(overrides: Partial<ColumnInfo> = {}): ColumnInfo {
  return {
    name: 'id',
    data_type: 'int',
    column_type: 'int(11)',
    nullable: false,
    key: 'PRI',
    default: null,
    extra: '',
    comment: '',
    position: 1,
    ...overrides,
  }
}

const structure: TableStructure = {
  database: 'shop',
  table: 'users',
  columns: [
    column({ name: 'id', extra: 'auto_increment' }),
    column({ name: 'name', data_type: 'varchar', column_type: 'varchar(50)', nullable: true, key: '', position: 2 }),
  ],
  indexes: [],
  foreign_keys: [],
  primary_key: ['id'],
  ddl: null,
}

describe('quoteIdentifier', () => {
  it('wraps a name in backticks', () => {
    expect(quoteIdentifier('users')).toBe('`users`')
  })

  it('doubles an embedded backtick', () => {
    expect(quoteIdentifier('we`ird')).toBe('`we``ird`')
  })

  it('leaves an injection attempt inert', () => {
    expect(quoteIdentifier('a`; DROP TABLE t; --')).toBe('`a``; DROP TABLE t; --`')
  })

  it('qualifies database and table', () => {
    expect(qualify('shop', 'order')).toBe('`shop`.`order`')
  })
})

describe('quoteValue', () => {
  it('renders NULL for null and undefined', () => {
    expect(quoteValue(null)).toBe('NULL')
    expect(quoteValue(undefined)).toBe('NULL')
  })

  it('leaves numbers unquoted', () => {
    expect(quoteValue(42)).toBe('42')
  })

  it('renders booleans as 1/0', () => {
    expect(quoteValue(true)).toBe('1')
    expect(quoteValue(false)).toBe('0')
  })

  it('escapes quotes and backslashes', () => {
    expect(quoteValue("O'Reilly")).toBe("'O\\'Reilly'")
    expect(quoteValue('a\\b')).toBe("'a\\\\b'")
  })

  it('escapes newlines', () => {
    expect(quoteValue('a\nb')).toBe("'a\\nb'")
  })

  it('decodes a binary cell through FROM_BASE64', () => {
    expect(quoteValue({ __binary__: 'AAE=', size: 2 })).toBe("FROM_BASE64('AAE=')")
  })
})

describe('statement templates', () => {
  it('builds a SELECT with a limit', () => {
    expect(buildSelect('shop', 'users', 10)).toBe('SELECT * FROM `shop`.`users` LIMIT 10;')
  })

  it('omits auto_increment columns from the INSERT template', () => {
    const sql = buildInsertTemplate(structure)
    expect(sql).toContain('(`name`)')
    expect(sql).not.toContain('`id`')
  })

  it('excludes the primary key from the UPDATE assignments but keys the WHERE on it', () => {
    const sql = buildUpdateTemplate(structure)
    expect(sql).toContain('SET\n  `name` = NULL')
    expect(sql).toContain('WHERE `id` = ?')
  })

  it('keys DELETE on the primary key', () => {
    expect(buildDeleteTemplate(structure)).toContain('WHERE `id` = ?')
  })

  it('falls back to an impossible predicate when there is no key at all', () => {
    const empty: TableStructure = { ...structure, primary_key: [], columns: [] }
    expect(buildDeleteTemplate(empty)).toContain('WHERE 1 = 0')
  })
})

describe('column helpers', () => {
  it('detects generated columns', () => {
    expect(isAutoGenerated(column({ extra: 'auto_increment' }))).toBe(true)
    expect(isAutoGenerated(column({ extra: 'STORED GENERATED' }))).toBe(true)
    expect(isAutoGenerated(column({ extra: '' }))).toBe(false)
  })

  it('classifies numeric types', () => {
    expect(isNumericType('bigint')).toBe(true)
    expect(isNumericType('DECIMAL')).toBe(true)
    expect(isNumericType('varchar')).toBe(false)
  })
})

describe('rowKey', () => {
  it('uses the primary key when present', () => {
    expect(rowKey({ id: 7, name: 'ann' }, structure)).toEqual({ id: 7 })
  })

  it('falls back to every column when there is no primary key', () => {
    const keyless = { ...structure, primary_key: [] }
    expect(rowKey({ id: 7, name: 'ann' }, keyless)).toEqual({ id: 7, name: 'ann' })
  })

  it('represents a missing value as null', () => {
    expect(rowKey({}, structure)).toEqual({ id: null })
  })
})

describe('canEditRows', () => {
  it('allows editing when a primary key exists', () => {
    expect(canEditRows(structure)).toBe(true)
  })

  it('allows a narrow key-less table', () => {
    expect(canEditRows({ primary_key: [], columns: structure.columns })).toBe(true)
  })

  it('refuses a wide key-less table', () => {
    const columns = Array.from({ length: 13 }, (_, index) => column({ name: `c${index}` }))
    expect(canEditRows({ primary_key: [], columns })).toBe(false)
  })

  it('refuses a table with no columns at all', () => {
    expect(canEditRows({ primary_key: [], columns: [] })).toBe(false)
  })
})

describe('statementAtCursor', () => {
  const script = 'SELECT 1;\nSELECT 2;\nSELECT 3'

  it('finds the first statement', () => {
    expect(statementAtCursor(script, 3)).toBe('SELECT 1')
  })

  it('finds a middle statement', () => {
    expect(statementAtCursor(script, 13)).toBe('SELECT 2')
  })

  it('finds the trailing statement without a semicolon', () => {
    expect(statementAtCursor(script, script.length)).toBe('SELECT 3')
  })

  it('returns an empty string for an empty script', () => {
    expect(statementAtCursor('', 0)).toBe('')
  })
})

describe('client-side export', () => {
  it('quotes cells containing a comma or a quote', () => {
    const csv = toCsv(['a', 'b'], [['x,y', 'he said "hi"']])
    expect(csv).toBe('a,b\n"x,y","he said ""hi"""')
  })

  it('writes an empty field for NULL', () => {
    expect(toCsv(['a'], [[null]])).toBe('a\n')
  })

  it('labels binary cells', () => {
    expect(toCsv(['a'], [[{ __binary__: 'AA==', size: 1 }]])).toBe('a\n[BLOB]')
  })

  it('produces one JSON object per row', () => {
    expect(JSON.parse(toJson(['a', 'b'], [[1, 'x']]))).toEqual([{ a: 1, b: 'x' }])
  })

  it('keeps nulls in JSON output', () => {
    expect(JSON.parse(toJson(['a'], [[null]]))).toEqual([{ a: null }])
  })
})
