/**
 * Client-side SQL helpers.
 *
 * These build *previews* and console starters only — every statement the app
 * actually runs against user data is generated server-side with bound
 * parameters. Quoting here still matters because the text lands in the console
 * where the user can execute it.
 */

import type { CellValue, ColumnInfo, TableStructure } from '../types'

export function quoteIdentifier(name: string): string {
  return `\`${String(name).replace(/`/g, '``')}\``
}

export function qualify(database: string, table: string): string {
  return `${quoteIdentifier(database)}.${quoteIdentifier(table)}`
}

export function quoteValue(value: CellValue | undefined): string {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? '1' : '0'
  if (typeof value === 'object' && '__binary__' in value) return `FROM_BASE64('${value.__binary__}')`
  const escaped = String(value)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
  return `'${escaped}'`
}

export function buildSelect(database: string, table: string, limit = 100): string {
  return `SELECT * FROM ${qualify(database, table)} LIMIT ${limit};`
}

export function buildInsertTemplate(structure: TableStructure): string {
  const columns = structure.columns.filter((column) => !isAutoGenerated(column))
  const names = columns.map((column) => quoteIdentifier(column.name)).join(', ')
  const values = columns.map((column) => defaultLiteralFor(column)).join(', ')
  return `INSERT INTO ${qualify(structure.database, structure.table)} (${names})\nVALUES (${values});`
}

export function buildUpdateTemplate(structure: TableStructure): string {
  const assignments = structure.columns
    .filter((column) => !structure.primary_key.includes(column.name))
    .map((column) => `  ${quoteIdentifier(column.name)} = ${defaultLiteralFor(column)}`)
    .join(',\n')
  return `UPDATE ${qualify(structure.database, structure.table)}\nSET\n${assignments}\nWHERE ${whereTemplate(structure)};`
}

export function buildDeleteTemplate(structure: TableStructure): string {
  return `DELETE FROM ${qualify(structure.database, structure.table)}\nWHERE ${whereTemplate(structure)};`
}

function whereTemplate(structure: TableStructure): string {
  const keys = structure.primary_key.length ? structure.primary_key : [structure.columns[0]?.name].filter(Boolean)
  return keys.map((key) => `${quoteIdentifier(String(key))} = ?`).join(' AND ') || '1 = 0'
}

function defaultLiteralFor(column: ColumnInfo): string {
  if (column.nullable) return 'NULL'
  return isNumericType(column.data_type) ? '0' : "''"
}

export function isAutoGenerated(column: ColumnInfo): boolean {
  return /auto_increment|DEFAULT_GENERATED|VIRTUAL GENERATED|STORED GENERATED/i.test(column.extra ?? '')
}

export function isNumericType(dataType: string): boolean {
  return /^(tinyint|smallint|mediumint|int|integer|bigint|decimal|numeric|float|double|bit|year)$/i.test(dataType)
}

/**
 * Picks the columns that identify a row for edit/delete. The primary key is
 * used when present; otherwise every column is matched, which is what Adminer
 * does for key-less tables.
 */
export function rowKey(row: Record<string, CellValue>, structure: { primary_key: string[]; columns: ColumnInfo[] }) {
  const keyColumns = structure.primary_key.length
    ? structure.primary_key
    : structure.columns.map((column) => column.name)
  const key: Record<string, CellValue> = {}
  for (const column of keyColumns) {
    // A BLOB cannot round-trip through a WHERE clause, so key-less tables with
    // binary columns are intentionally left un-editable by the caller.
    key[column] = row[column] ?? null
  }
  return key
}

export function canEditRows(structure: { primary_key: string[]; columns: ColumnInfo[] }): boolean {
  if (structure.primary_key.length > 0) return true
  return structure.columns.length > 0 && structure.columns.length <= 12
}

/** Splits a script the same way the backend does, for "run statement at cursor". */
export function statementAtCursor(sql: string, cursor: number): string {
  const before = sql.lastIndexOf(';', Math.max(0, cursor - 1))
  const afterIndex = sql.indexOf(';', cursor)
  const start = before === -1 ? 0 : before + 1
  const end = afterIndex === -1 ? sql.length : afterIndex
  return sql.slice(start, end).trim()
}

export function toCsv(columns: string[], rows: CellValue[][]): string {
  const cell = (value: CellValue) => {
    if (value === null || value === undefined) return ''
    const text = typeof value === 'object' && '__binary__' in value ? '[BLOB]' : String(value)
    return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text
  }
  return [columns.join(','), ...rows.map((row) => row.map(cell).join(','))].join('\n')
}

export function toJson(columns: string[], rows: CellValue[][]): string {
  return JSON.stringify(
    rows.map((row) => Object.fromEntries(columns.map((column, index) => [column, row[index] ?? null]))),
    null,
    2,
  )
}
