// ----- GLOBAL OBJECTS ----- //

export const testPositions = {
	// chariot_red_left: [0, 0],
	horse_red_left: [1, 0],
	// elephant_red_left: [2, 0],
	// advisor_red_left: [3, 0],
	general_red: [4, 0],
	// advisor_red_right: [5, 0],
	// elephant_red_right: [6, 0],
	// horse_red_right: [7, 0],
	// chariot_red_right: [8, 0],
	// cannon_red_left: [1, 2],
	// cannon_red_right: [7, 2],
	// soldier_red_1: [0, 3],
	// soldier_red_2: [2, 3],
	// soldier_red_3: [4, 3],
	// soldier_red_4: [6, 3],
	// soldier_red_5: [8, 3],
	chariot_black_left: [0, 9],
	// horse_black_left: [1, 9],
	// elephant_black_left: [2, 9],
	// advisor_black_left: [3, 9],
	general_black: [4, 9],
	// advisor_black_right: [5, 9],
	// elephant_black_right: [6, 9],
	// horse_black_right: [7, 9],
	// chariot_black_right: [8, 9],
	// cannon_black_left: [1, 7],
	// cannon_black_right: [7, 7],
	// soldier_black_1: [0, 6],
	// soldier_black_2: [2, 6],
	// soldier_black_3: [4, 6],
	// soldier_black_4: [6, 6],
	// soldier_black_5: [8, 6],
};

// Library of Default Positions at Game Start [file, rank]
export const defaultPositions = {
	chariot_red_left: [0, 0],
	horse_red_left: [1, 0],
	elephant_red_left: [2, 0],
	advisor_red_left: [3, 0],
	general_red: [4, 0],
	advisor_red_right: [5, 0],
	elephant_red_right: [6, 0],
	horse_red_right: [7, 0],
	chariot_red_right: [8, 0],
	cannon_red_left: [1, 2],
	cannon_red_right: [7, 2],
	soldier_red_1: [0, 3],
	soldier_red_2: [2, 3],
	soldier_red_3: [4, 3],
	soldier_red_4: [6, 3],
	soldier_red_5: [8, 3],
	chariot_black_left: [0, 9],
	horse_black_left: [1, 9],
	elephant_black_left: [2, 9],
	advisor_black_left: [3, 9],
	general_black: [4, 9],
	advisor_black_right: [5, 9],
	elephant_black_right: [6, 9],
	horse_black_right: [7, 9],
	chariot_black_right: [8, 9],
	cannon_black_left: [1, 7],
	cannon_black_right: [7, 7],
	soldier_black_1: [0, 6],
	soldier_black_2: [2, 6],
	soldier_black_3: [4, 6],
	soldier_black_4: [6, 6],
	soldier_black_5: [8, 6],
};

// Notation Rules Used for creating Notated Board in Board State
export const notationPiece = {
	general: "K",
	advisor: "A",
	elephant: "E",
	horse: "H",
	chariot: "R",
	cannon: "C",
	soldier: "P",
};

// Library of Defined Paths for Certain Pieces
export const definedPathsRules = {
	red: {
		elephant: [
			[2, 0],
			[6, 0],
			[0, 2],
			[4, 2],
			[8, 2],
			[2, 4],
			[6, 4],
		],
		advisor: [
			[3, 0],
			[5, 0],
			[4, 1],
			[3, 2],
			[5, 2],
		],
		general: [
			[3, 0],
			[4, 0],
			[5, 0],
			[3, 1],
			[4, 1],
			[5, 1],
			[3, 2],
			[4, 2],
			[5, 2],
		],
	},

	black: {
		elephant: [
			[2, 9],
			[6, 9],
			[0, 7],
			[4, 7],
			[8, 7],
			[2, 5],
			[6, 5],
		],
		advisor: [
			[3, 9],
			[5, 9],
			[4, 8],
			[3, 7],
			[5, 7],
		],
		general: [
			[3, 9],
			[4, 9],
			[5, 9],
			[3, 8],
			[4, 8],
			[5, 8],
			[3, 7],
			[4, 7],
			[5, 7],
		],
	},
};
