import { useEffect, useMemo, useState } from 'react'

import { isAutoGenerated, isNumericType } from '../lib/sql'
import type { CellValue, ColumnInfo } from '../types'
import { CloseIcon } from './Icons'

interface Props {
  mode: 'insert' | 'edit'
  columns: ColumnInfo[]
  row?: Record<string, CellValue>
  onCancel: () => void
  onSave: (values: Record<string, unknown>) => Promise<void> | void
}

interface FieldState {
  text: string
  isNull: boolean
}

function initialState(columns: ColumnInfo[], row?: Record<string, CellValue>): Record<string, FieldState> {
  const state: Record<string, FieldState> = {}
  for (const column of columns) {
    const value = row?.[column.name]
    if (row) {
      state[column.name] = {
        text: value === null || value === undefined ? '' : stringify(value),
        isNull: value === null || value === undefined,
      }
    } else {
      // New rows start at the column default; nullable columns start as NULL.
      state[column.name] = {
        text: column.default === null || column.default === undefined ? '' : String(column.default),
        isNull: column.nullable && column.default === null,
      }
    }
  }
  return state
}

function stringify(value: CellValue): string {
  if (value === null || value === undefined) return ''
  if (typeof value === 'object' && '__binary__' in value) return ''
  return String(value)
}

export function RowEditor({ mode, columns, row, onCancel, onSave }: Props) {
  const editable = useMemo(
    () => columns.filter((column) => mode === 'edit' || !isAutoGenerated(column)),
    [columns, mode],
  )
  const [fields, setFields] = useState<Record<string, FieldState>>(() => initialState(editable, row))
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === 'Escape') onCancel()
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [onCancel])

  function update(name: string, patch: Partial<FieldState>) {
    setFields((current) => ({ ...current, [name]: { ...current[name], ...patch } }))
  }

  async function handleSave() {
    const values: Record<string, unknown> = {}
    for (const column of editable) {
      const field = fields[column.name]
      if (!field) continue
      if (field.isNull) {
        values[column.name] = null
      } else if (isNumericType(column.data_type) && field.text.trim() !== '') {
        const numeric = Number(field.text)
        values[column.name] = Number.isNaN(numeric) ? field.text : numeric
      } else {
        values[column.name] = field.text
      }
    }
    setSaving(true)
    try {
      await onSave(values)
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="modal-backdrop" onMouseDown={onCancel}>
      <div
        className="modal modal-lg"
        role="dialog"
        aria-modal="true"
        aria-label={mode === 'insert' ? 'Insert row' : 'Edit row'}
        onMouseDown={(event) => event.stopPropagation()}
      >
        <div className="modal-header">
          <h2 className="modal-title">{mode === 'insert' ? 'Insert row' : 'Edit row'}</h2>
          <button type="button" className="icon-btn" onClick={onCancel} aria-label="Close">
            <CloseIcon size={16} />
          </button>
        </div>

        <div className="row-editor-fields">
          {editable.map((column) => {
            const field = fields[column.name]
            const multiline = /text|blob|json/i.test(column.data_type)
            return (
              <div className="row-editor-field" key={column.name}>
                <div className="row-editor-label">
                  <strong>{column.name}</strong>
                  <code>{column.column_type}</code>
                  {column.key === 'PRI' ? <span className="badge badge-pk">PK</span> : null}
                  {column.extra ? <span className="badge">{column.extra}</span> : null}
                </div>
                <div className="row-editor-input">
                  {multiline ? (
                    <textarea
                      value={field?.text ?? ''}
                      disabled={field?.isNull}
                      rows={3}
                      onChange={(event) => update(column.name, { text: event.target.value })}
                    />
                  ) : (
                    <input
                      value={field?.text ?? ''}
                      disabled={field?.isNull}
                      onChange={(event) => update(column.name, { text: event.target.value })}
                    />
                  )}
                  <label className={`null-toggle${column.nullable ? '' : ' is-disabled'}`}>
                    <input
                      type="checkbox"
                      checked={field?.isNull ?? false}
                      disabled={!column.nullable}
                      onChange={(event) => update(column.name, { isNull: event.target.checked })}
                    />
                    NULL
                  </label>
                </div>
              </div>
            )
          })}
        </div>

        <div className="modal-actions">
          <button type="button" className="btn" onClick={onCancel}>
            Cancel
          </button>
          <button type="button" className="btn btn-primary" onClick={() => void handleSave()} disabled={saving}>
            {saving ? 'Saving…' : mode === 'insert' ? 'Insert' : 'Save changes'}
          </button>
        </div>
      </div>
    </div>
  )
}
