name: Backend CI / Test on Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'
    types: [opened, synchronize, reopened, edited, ready_for_review, labeled]

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  backend-ci:
    name: Backend PR CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend/gemini-proxy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Checkstyle (main + test)
        run: mvn checkstyle:checkstyle@checkstyle-all

      - name: Run tests with Jacoco
        run: mvn clean test jacoco:report -f pom.xml

      - name: Archive jacoco report
        run: zip -r jacoco-report.zip target/site/jacoco
      
      - name: Upload jacoco report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/gemini-proxy/jacoco-report.zip

      - name: Verify build status
        run: echo "✅ Backend PR CI completed successfully"
